name: LobbyNitroGames
author: jeje2208-Saulunaire
main: main.Main
version: 1.0.0
commands:
  setGrade:
    description: Modifier le Grade d'un joueur
  addVIP:
    description: Ajouter un grade a un joueur
  armor:
    description: armor